name: Swing Agent Hourly

# Trigger: hourly + manual
on:
  schedule:
    - cron: "0 * * * 1-5"  # Every hour, Monday to Friday
  workflow_dispatch:       # Manual trigger

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install yfinance gspread oauth2client

      # Step 4: Run the swing agent script
      - name: Run Swing Agent
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          python swing_agent.py
