name: Swing Agent Hourly

on:
  schedule:
    - cron: "0 * * * 1-5"   # Every hour, Mon-Fri
  workflow_dispatch:        # Manual trigger

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance gspread oauth2client

      - name: Run Swing Agent
  env:
    EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
    EMAIL_TO: ${{ secrets.EMAIL_TO }}
    APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
    GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
  run: python swing_agent.py
